$lock_cmd = ~/.config/quickshell/Scripts/Session/lock.sh
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

listener {
    timeout = 1800 # 30mins
    on-timeout = $suspend_cmd
}
