$lock_cmd = pidof hyprlock || hyprlock -c ~/.local/state/quickshell/user/generated/hyprlock.conf
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

listener {
    timeout = 1800 # 30mins
    on-timeout = $suspend_cmd
}
