#!/usr/bin/env python3
"""Generate the qmldir files that let qmllint and qmlls resolve Carbon's `qs.*` module imports.

Quickshell synthesizes a qmldir for every config directory at runtime, but the QML tooling
cannot see those. Any directory imported as a `qs.*` module therefore needs a real qmldir
checked in. Quickshell skips synthesis for a directory that already has one, so each generated
file must list every type in that directory, singletons included.

Usage: qmldir-sync.py <quickshell-dir> [--check]
"""

import re
import sys
from pathlib import Path

SINGLETON = re.compile(r"^\s*pragma\s+Singleton", re.M)
MODULE_IMPORT = re.compile(r"^\s*import\s+qs(?:\.([A-Za-z0-9_.]+))?\b", re.M)

HEADER = "# Generated by Scripts/Diagnostics/qmldir-sync.py - do not edit by hand.\n"


def module_dirs(root: Path) -> list[Path]:
    """Every directory imported as a `qs.*` module somewhere in the tree."""
    found = set()
    for qml in root.rglob("*.qml"):
        for match in MODULE_IMPORT.finditer(qml.read_text()):
            found.add(root.joinpath(*match.group(1).split(".")) if match.group(1) else root)
    return sorted(d for d in found if d.is_dir())


def render(directory: Path) -> str:
    """The qmldir contents for one module directory."""
    lines = [HEADER]
    for qml in sorted(directory.glob("*.qml")):
        if not qml.stem[:1].isupper():
            continue
        prefix = "singleton " if SINGLETON.search(qml.read_text()[:400]) else ""
        lines.append(f"{prefix}{qml.stem} 1.0 {qml.name}\n")
    return "".join(lines)


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    positional = [a for a in args if not a.startswith("-")]
    if len(positional) != 1:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2

    root = Path(positional[0]).resolve()
    if not root.is_dir():
        print(f"qmldir-sync: not a directory: {root}", file=sys.stderr)
        return 2

    stale = []
    for directory in module_dirs(root):
        target = directory / "qmldir"
        wanted = render(directory)
        if target.exists() and target.read_text() == wanted:
            continue
        if check:
            stale.append(target.relative_to(root))
        else:
            target.write_text(wanted)
            print(f"qmldir-sync: wrote {target.relative_to(root)}")

    if stale:
        print("qmldir-sync: stale qmldir files (run qmllint.sh --sync-qmldir):", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
